// <auto-generated />
using System;
using BEDatabaseFinalProject.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BEDatabaseFinalProject.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    partial class AplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BEDatabaseFinalProject.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Usario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Cliente");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BEDatabaseFinalProject.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorreoEmpleado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotelNombreHotel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("BEDatabaseFinalProject.Entities.EmpleadoHabitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadoIdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("HabitacionNumHabitacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmpleadoHabitacions");
                });

            modelBuilder.Entity("BEDatabaseFinalProject.Entities.EmpleadoReserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("ReservaHabitacionReservada")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmpleadoReservas");
                });

            modelBuilder.Entity("BEDatabaseFinalProject.Entities.Gerente", b =>
                {
                    b.Property<int>("ClaveGerente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaveGerente"));

                    b.Property<string>("CorreoGerente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotelNombreHotel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumTelefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClaveGerente");

                    b.ToTable("Gerentes");
                });

            modelBuilder.Entity("BEDatabaseFinalProject.Entities.Habitacion", b =>
                {
                    b.Property<int>("NumHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumHabitacion"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<int>("GerenteClaveGerente")
                        .HasColumnType("int");

                    b.HasKey("NumHabitacion");

                    b.ToTable("Habitaciones");
                });

            modelBuilder.Entity("BEDatabaseFinalProject.Entities.Hotel", b =>
                {
                    b.Property<string>("NombreHotel")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Ingresos")
                        .HasColumnType("float");

                    b.HasKey("NombreHotel");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("BEDatabaseFinalProject.Entities.Reserva", b =>
                {
                    b.Property<int>("HabitacionReservada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HabitacionReservada"));

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<int>("GerenteClaveGerente")
                        .HasColumnType("int");

                    b.Property<int>("NumHuesped")
                        .HasColumnType("int");

                    b.HasKey("HabitacionReservada");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("BEDatabaseFinalProject.Entities.ClienteExtranjero", b =>
                {
                    b.HasBaseType("BEDatabaseFinalProject.Entities.Cliente");

                    b.Property<double>("PagoMonedaExtranjera")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("ClienteExtranjero");
                });

            modelBuilder.Entity("BEDatabaseFinalProject.Entities.ClienteNacional", b =>
                {
                    b.HasBaseType("BEDatabaseFinalProject.Entities.Cliente");

                    b.Property<double>("PagoMonedaNacional")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("ClienteNacional");
                });
#pragma warning restore 612, 618
        }
    }
}
